# Generated by Django 4.2.7 on 2023-11-19 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attribute", "0001_initial"),
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="adsattributevalueoption",
            name="ads_attribute_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="value_options",
                to="ads.adsattributevalue",
            ),
        ),
        migrations.AddField(
            model_name="adsattributevalueoption",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="attribute.attributeoption",
            ),
        ),
        migrations.AddField(
            model_name="adsattributevalue",
            name="ads",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_values",
                to="ads.ads",
            ),
        ),
        migrations.AddField(
            model_name="adsattributevalue",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attribute.attribute"
            ),
        ),
        migrations.AddField(
            model_name="ads",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.district"
            ),
        ),
        migrations.AddField(
            model_name="ads",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_category",
                to="ads.subcategory",
            ),
        ),
    ]
