# Generated by Django 4.2.7 on 2023-11-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsAttributeValueProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ads.ads',),
        ),
        migrations.CreateModel(
            name='AdsProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ads.ads',),
        ),
    ]
