# Generated by Django 4.2.7 on 2023-11-19 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverLicence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level_choice",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("B+E", "Be"),
                            ("C+E", "Ce"),
                            ("D+E", "De"),
                        ],
                        default="None",
                        max_length=4,
                    ),
                ),
                ("percentage", models.IntegerField(default=5)),
                ("state", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=30)),
                ("specially", models.CharField(max_length=50)),
                ("start_date", models.DateTimeField()),
                ("finished_date", models.DateTimeField()),
                ("new_field", models.IntegerField(default=0)),
                ("precentage", models.IntegerField(default=25)),
                ("work_state", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position_name", models.CharField(max_length=30)),
                ("employer", models.CharField(max_length=50)),
                ("about_work", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("finished_date", models.DateTimeField()),
                ("precentage", models.IntegerField(default=40)),
                ("new_field", models.IntegerField(default=0)),
                ("work_state", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("resume", models.FileField(upload_to="")),
                (
                    "other_experience",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("hobby", models.TextField()),
                (
                    "driver_licence",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="userprofile.driverlicence",
                    ),
                ),
                (
                    "education",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="userprofile.education",
                    ),
                ),
                (
                    "experience",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userprofile.experience",
                    ),
                ),
                ("language", models.ManyToManyField(to="userprofile.language")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobForUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type_work", models.CharField(max_length=50)),
                (
                    "time_job",
                    models.CharField(
                        choices=[
                            ("Tuliq stavkada bandlik", "Fully"),
                            ("Tuliq bolmagan bandlik", "No Fully"),
                        ],
                        default="Tuliq stavkada bandlik",
                        max_length=30,
                    ),
                ),
                (
                    "type_job",
                    models.CharField(
                        choices=[
                            ("Doimiy bandlik", "Always Busy"),
                            ("Vaqtinchalik bandlik", "Temporary Busy"),
                        ],
                        default="Doimiy bandlik",
                        max_length=30,
                    ),
                ),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("SUM", "Sum"), ("EURO", "Euro")],
                        default="SUM",
                        max_length=4,
                    ),
                ),
                (
                    "day_or_month",
                    models.CharField(
                        choices=[("day", "Day"), ("month", "Month")],
                        default="day",
                        max_length=6,
                    ),
                ),
                ("least_price", models.IntegerField(default=0)),
                (
                    "distirct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.district",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
